# Generated by Django 2.0.1 on 2018-04-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='molbank',
            fields=[
                ('ID', models.CharField(default='DUMMY_ID', max_length=10, primary_key=True, serialize=False)),
                ('SMILES', models.CharField(default='DUMMY_SMILES', max_length=150)),
                ('SAMPLE_CODE', models.CharField(default='DUMMY_SAMPLE_CODE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=100)),
                ('chemist', models.BooleanField(default=False)),
                ('biologist', models.BooleanField(default=False)),
                ('spectral', models.BooleanField(default=False)),
            ],
        ),
    ]
