# Generated by Django 2.0.1 on 2018-04-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molbank',
            options={'permissions': (('is_admin', 'MB: ADMIN'), ('is_chem', 'MB: CHEM'), ('is_bio', 'MB: BIO'), ('is_slab', 'MB: SLAB'))},
        ),
    ]
