# Generated by Django 2.0.1 on 2018-04-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molbank', '0002_auto_20180403_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='allplates',
            fields=[
                ('Project', models.CharField(max_length=4)),
                ('Position_in_Array', models.CharField(blank=True, max_length=4, null=True)),
                ('sub_project', models.CharField(blank=True, max_length=4, null=True)),
                ('MTP_Plate_No', models.CharField(blank=True, max_length=4, null=True)),
                ('Structure', models.CharField(blank=True, max_length=1, null=True)),
                ('Solution_PT_Barcode', models.IntegerField(blank=True, null=True)),
                ('Array_PT_Barcode', models.CharField(blank=True, max_length=10, null=True)),
                ('Tray_PT_Barcode', models.IntegerField(blank=True, null=True)),
                ('Neat_sample_Barcode', models.IntegerField(blank=True, null=True)),
                ('Array_NS_Barcode', models.IntegerField(blank=True, null=True)),
                ('Tray_NS_Barcode', models.IntegerField(blank=True, null=True)),
                ('Smiles', models.CharField(max_length=500)),
                ('Sample_code', models.CharField(db_column='sample_code', max_length=20, primary_key=True, serialize=False)),
                ('Molecular_Weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Molecular_Formula', models.CharField(max_length=500)),
                ('CLogP', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Name', models.CharField(max_length=500)),
                ('NMR', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Mass', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('HPLC_or_LCMS', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Solubility', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('No_of_Rings', models.IntegerField()),
                ('No_of_nitrogens', models.IntegerField()),
                ('No_of_Oxygens', models.IntegerField()),
                ('TPSA', models.DecimalField(decimal_places=3, max_digits=10)),
                ('No_of_Sulphur', models.IntegerField()),
                ('Sample_Weight_submitted', models.CharField(max_length=10)),
                ('Purity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('IUPAC_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Date_of_approval', models.DateField(blank=True, null=True)),
                ('Date_of_Submission', models.DateField(blank=True, null=True)),
                ('Scientist_name', models.CharField(max_length=30)),
                ('Reference_syn_or_bio', models.CharField(blank=True, max_length=4, null=True)),
                ('Known_bio_activity', models.CharField(blank=True, max_length=4, null=True)),
                ('Natural_or_Synthetic', models.CharField(blank=True, max_length=4, null=True)),
                ('Physical_state', models.CharField(blank=True, max_length=4, null=True)),
                ('Sample_in', models.CharField(blank=True, max_length=4, null=True)),
                ('Sample_out', models.CharField(blank=True, max_length=4, null=True)),
                ('Miscellaneous', models.CharField(blank=True, max_length=4, null=True)),
                ('Optical_Rotation', models.CharField(blank=True, max_length=4, null=True)),
                ('Institute', models.CharField(max_length=10)),
            ],
        ),
    ]
